FROM amazonlinux:latest



sudo yum update
sudo yum install docker -y
sudo service docker start
sudo usermod -a -G docker ec2-user
sudo systemctl enable docker.service # Enable the service
sudo systemctl start docker                 # Start the Docker daemon.
sudo docker images                             # Show local images
sudo docker pull tutum/wordpress                    # pull the image
sudo docker run -d -p 80:80 -p 443:443 tutum/wordpress   #  Run container
sudo curl http://localhost/                         # Test container
sudo docker stop                                    # Stop container
sudo docker ps -a                                 # Show container list
sudo docker export 633748a43e01 - blog.tar                          # Export container
cat blog.tar | sudo docker import - tutum/wordpress blog.tar        # Import container
docker pull ubuntu
docker -it ubuntu
CMD ["/bin/bash", "/start.sh"]